### ISSUE TITLE
November Foundation for Public Code community call

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#120]
This call will take place on 19 November 2020 at 14.00 UTC.

We still need to pick a topic - please vote on the suggestions below, or add your own!

**Comment by ElenaFdR** [comment]
Suggestions made so far for this call topic are:

- from @lscheske: What it means to be a radically open organizationi. We're having a week of workshops for staff this week about how we work, including version control, making contributing easy, open documentation, building communities, and professionalism, plain English, coherent style, and documenting maturity. All of these practices flow out of our decision to be open, unless (as set out in [our communications principles](https://about.publiccode.net/activities/communication/communication-principles.html))
-  from @Ainali: let's talk about different FOSS policies and strategy and how we can refer to them or use them as tools. This could be prompted by the recent publication of the European Commission strategy https://ec.europa.eu/info/sites/info/files/en_ec_open_source_strategy_2020-2023.pdf

**Comment by ElenaFdR** [comment]
We've decided to follow the rocket, and talk about the new EC strategy. [See the agenda](https://hackmd.io/9THmWbpQTLi8L9UIzczSyw) for more detail.

**Comment by ElenaFdR** [comment]
Tasks to complete the call:

- [x] draft agenda
- [ ] send invitations and tweet about it
- [x] set up notes document
- [ ] have call and take notes
- [ ] write up notes as a blogpost
- [ ] share draft blogpost with call attendees for review
- [ ] publish blogpost!

**Comment by clausmullie** [comment]
This community call has happened. Seeing as it was over a year ago, I'm not sure it is worth prioritising the write up. I will close this issue, but if anyone feels strongly about this, please feel free to reopen (and write up the minutes).
