### ISSUE TITLE
Blogpost about Dutch 'publieke belang, publieke software?' debate 

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#122]
@felixfaassen has a strong reaction to [this debate](https://twitter.com/Opendatanl/status/1326510677272498176) this morning, and would like to blog about some fundamental FOSS concepts that were not very clear in the discussion.

Outstanding questions:

- which platform to publish this on (probably https://opensource.pleio.nl/)
- language? (probably Dutch)

**Comment by bvhme** [comment]
That sounds like a great platform for this, and we could publish an English version on our blog if time permits.

**Comment by felixfaassen** [comment]
Closing this issue, sorry I did not follow up or have been explicit about deprioritizing it. Also there a lot of posts on the pleio also expressing my thoughts about this meeting last december.

**Comment by ElenaFdR** [comment]
@felixfaassen, can you provide a link to a good Pleio post for posterity?

**Comment by felixfaassen** [comment]
- https://opensource.pleio.nl/news/view/66c0f1ec-8e62-462d-a018-199e594c1acc/terugkijken-ibestuur-thuisdebat-publiek-belang-publieke-software
- https://opensource.pleio.nl/news/view/4fdc0823-d53f-46f4-b2d2-8597f4cffa07/open-tenzij-we-aanbesteden
- https://opensource.pleio.nl/news/view/51db84cf-08f2-4c1d-b85d-94ed6ff52cb4/naar-een-andere-manier-van-denken-over-ict-inkopen
