### ISSUE TITLE
September 2020 Foundation for Public Code community call

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#124]
This call took place on 11 September 2020.

Tasks to complete the call:

- [x] draft agenda
- [x] send invitations and tweet about it
- [x] set up notes document
- [x] have call and take notes
- [ ] write up notes as a blogpost
- [ ] share draft blogpost with call attendees for review
- [ ] publish blogpost!

**Comment by clausmullie** [comment]
Seeing as this was over a year ago, I'm not sure it is worth prioritising the write up. I will close this issue, but if anyone feels strongly about this, please feel free to reopen (and write up the minutes).
