### ISSUE TITLE
Blog post on community calls

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/blog#138]
I would like to make a blog post on our thinking on community calls and how we use them as a way of really collaborating in the open (and not just being an entrance point for non-staff). Having this would make it easier for anyone to understand what we mean by them. I could take a stab at a first draft and then perhaps @bvhme could take a look to see if I manage to capture the spirit correctly. After this is written, perhaps our pages on about could also be improved. Does this sound like a useful idea?

**Comment by bvhme** [comment]
Yeah, I love this! Let me know when I can review something.

**Comment by clausmullie** [comment]
Closing this issue for now as it is over a year old. We can reopen this once it becomes a priority.
