### ISSUE TITLE
Should we number our newsletters?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#157]
This seems to be very common among newsletters I'm subscribed to. 

Our newsletters have always been identified with a season and date range, so I'm not sure what extra clarity/value individual sequential numbering will provide.

Perhaps this makes it easier to identify milestone newsletters? (Our 50th or 100th?)

Thoughts welcome!

**Comment by Ainali** [comment]
I don't think this adds much value, even though I recognize the pattern from elsewhere. But when going back, it's much easier for me to remember, or refer to, the newsletter of September 2020, than trying to figure out what number it had.

**Comment by bvhme** [comment]
I think numbers are a production artifact and I usually think they are a distraction.

**Comment by ElenaFdR** [comment]
It sounds like we don't see any additional value to this, so I'm going to close this issue.
