### ISSUE TITLE
May 2021 Foundation for Public Code community call

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#183]
This call will take place on Thursday, 20 May 2021 at 15.00 CEST.
If you have a topic proposal, please comment below!
We'll choose the topic the week before the call date.

Potential call topic ideas:

- what we should do next to scale the Foundation for Public Code
- what we learned from publishing our first annual report
- how to grow/deepen our codebase stewardship practice?

**Comment by AlbaRoza** [comment]
And what about a second session on our board members' selection process?

**Comment by ElenaFdR** [comment]
@AlbaRoza, I strongly support the idea of continuing to have this dicussion in public, but propose we wait until @nebster can join us again. This means we'll have a different topic for this month's community call.

**Comment by ElenaFdR** [comment]
The topic is now confirmed! We'll talk about what we can do to increase the scale and impact of our stewardship practice beyond the codebases we work with directly.

**Comment by clausmullie** [comment]
This call has passed, and we now have a mailing list for community calls, so I'm going to close this issue.
