### ISSUE TITLE
June 2021 Foundation community call

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#198]
This call will take place on Thursday, 17 June 2021 at 15.00 CEST/13.00 UTC.
If you have a topic proposal, please comment below!
We'll choose the topic the week before the call date.

Potential call topic ideas:

- next steps in recruiting new board members/advisors
- what we learned from publishing our first annual report

**Comment by Ainali** [comment]
The annual report might be interesting for our community, but not only the process of putting it together (that seems like more of a lecture), but also the content of it.

**Comment by ElenaFdR** [comment]
Update: we've chosen to discuss our approach to documentation, and specifically content maintenance. This has been prompted by recent experiences with not being able to find records of important decisions, while marvelling at how out of date our content has become.

**Comment by ElenaFdR** [comment]
@Ainali Re the annual report, I'd like to discuss it once:

- we're completely finished and have had time to reflect on our experiences producing it (maybe the call should be our retro?)
- it's been live for long enough for people to read it

**Comment by clausmullie** [comment]
This call has passed, and we now have a mailing list for community calls, so I'm going to close this issue.
