### ISSUE TITLE
Label for blog posts

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/blog#23]
Should we add a separate label for blog posts? That would make easier to distinguish from other sorts of improvements to the blog.

**Comment by ElenaFdR** [comment]
Would you use this on both issues and PRs?

**Comment by Ainali** [comment]
I think it will mostly affect PR's, but for the times that we actually creates an issue before writing the blog post, why not?

**Comment by ElenaFdR** [comment]
Sounds good!

**Comment by ElenaFdR** [comment]
I've done this now.
