### ISSUE TITLE
Switch to simpler contributing process?

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/blog#345]
The process we have, with a develop branch and release branches, is very rigorous, but perhaps a bit overkill since we're now in a state where the normal pull request is just a simple blog post. Having two review process for the same blog post, often back-to-back of each other, does not add as much value as it is tedious to do it. Can we switch to just merging to main?

**Comment by ericherman** [comment]
I would not oppose.

**Comment by Ainali** [comment]
I suggest we then:

- [ ] Switch default branch to main
- [ ] Update [our instructions on About](https://about.publiccode.net/activities/communication/blogging.html) to make clear release branches are not used
- [ ] Mention the main branch in [CONTRIBUTING.md#making-a-pull-request](https://github.com/publiccodenet/blog/blob/develop/CONTRIBUTING.md#making-a-pull-request)
- [ ] Delete the develop branch

Did I miss anything?

**Comment by ericherman** [comment]
I think that's it -- updating About was the thing I was thinking we'd need to remember.

**Comment by Ainali** [comment]
The branches have been changed!
