### ISSUE TITLE
Add missing functionality to blog

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/blog#4]
## Missing

- [X] about this blog
- [X] Populate contact page (with HTML and our info) - solved by deleting
- [x] something that makes at least the most recent post text appear on the index
- [x] front matter rendering for posts
- [x] internal nav: eg breadcrumbs to get from post back to index (not needed because you can click on the word 'blog)
- [x] external nav: link to http site (see [PR #15](https://github.com/publiccodenet/jekyll-theme/pull/15))
- [ ] internal nav: link to the blog's about
- [ ] favicon (warns GitHub)
- [ ] RSS feed?
- [ ] social sharing
- [ ] fix rendering of blog name

## Not currently relevant

- [ ] layout file for posts
- [ ] Go back to https://jekyllrb.com/docs/configuration/front-matter-defaults/ to set up default post layout after reading about layouts
- [ ] [data files](https://jekyllrb.com/docs/datafiles/) - can be used to organise site by author!
- [ ] [collections](https://jekyllrb.com/docs/collections/) of posts

**Comment by ElenaFdR** [comment]
Desired blogpost attributes:

- date
- author
- category
- tag
- file attachments

**Comment by bvhme** [comment]
I'd start without a layout file for posts, and do that when need arises.
Just start off with the default.

**Comment by ElenaFdR** [comment]
Removed frontmatter:
---
layout: post
title:  "To do and outstanding questions!"
date:   2019-05-23 
categories: sandbox
author: elena
---

**Comment by Ainali** [comment]
I think that the frontmatter should include `type:blogpost` as well. This makes the right column print out **This blogpost** above the date and author rather than just **This**.

**Comment by Ainali** [comment]
A feed would be nice. Perhaps [Jekyll feed](https://github.com/jekyll/jekyll-feed)?
