### ISSUE TITLE
Improve the resilience of our links in blogposts

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/blog#458]
I was reading up on jekyll and realised we could improve best practice in how we interlink blog posts when reading https://www.digitalocean.com/community/tutorials/how-to-control-urls-and-links-in-jekyll

Currently we use absolute links when we link from one blog post to the other (https://blog.publiccode.net/slug).
This works well for now, but would break everything if the base url would change (and won't work on local builds).

A solution would be to use dynamic linking with liquid based on post file names.
`[Link Text]({% post_url filename %})`

This would make the blog more resilient for changes in the future, and add another layer of link checking as jekyll cannot complete the build when a missing filename is specified

**Comment by Ainali** [comment]
Have you confirmed in a local branch that it works for our blog?
